In [44]:
!pip install scikit-surprise
import pandas as pd
import numpy

Requirement already satisfied: scikit-surprise in /usr/local/lib/python3.7/dist-packages (1.1.1)
Requirement already satisfied: numpy>=1.11.2 in /usr/local/lib/python3.7/dist-packages (from scikit-surprise) (1.21.5)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-surprise) (1.4.1)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.7/dist-packages (from scikit-surprise) (1.15.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-surprise) (1.1.0)

In [45]:
df =pd.read_csv('/content/udemy_output_All_IT__Software_p1_p626.csv')
df

,id,title,url,is_paid,num_subscribers,avg_rating,avg_rating_recent,rating,num_reviews,is_wishlisted,num_published_lectures,num_published_practice_tests,created,published_time,discount_price__amount,discount_price__currency,discount_price__price_string,price_detail__amount,price_detail__currency,price_detail__price_string
0,762616,The Complete SQL Bootcamp 2020: Go from Zero t...,/course/the-complete-sql-bootcamp/,True,295509,4.66019,4.67874,4.67874,78006,False,84,0,2016-02-14T22:57:48Z,2016-04-06T05:16:11Z,455.0,INR,₹455,8640.0,INR,"₹8,640"
1,937678,Tableau 2020 A-Z: Hands-On Tableau Training fo...,/course/tableau10/,True,209070,4.58956,4.60015,4.60015,54581,False,78,0,2016-08-22T12:10:18Z,2016-08-23T16:59:49Z,455.0,INR,₹455,8640.0,INR,"₹8,640"
2,1361790,PMP Exam Prep Seminar - PMBOK Guide 6,/course/pmp-pmbok6-35-pdus/,True,155282,4.59491,4.59326,4.59326,52653,False,292,2,2017-09-26T16:32:48Z,2017-11-14T23:58:14Z,455.0,INR,₹455,8640.0,INR,"₹8,640"
3,648826,The Complete Financial Analyst Course 2020,/course/the-complete-financial-analyst-course/,True,245860,4.54407,4.53772,4.53772,46447,False,338,0,2015-10-23T13:34:35Z,2016-01-21T01:38:48Z,455.0,INR,₹455,8640.0,INR,"₹8,640"
4,637930,An Entire MBA in 1 Course:Award Winning Busine...,/course/an-entire-mba-in-1-courseaward-winning...,True,374836,4.47080,4.47173,4.47173,41630,False,83,0,2015-10-12T06:39:46Z,2016-01-11T21:39:33Z,455.0,INR,₹455,8640.0,INR,"₹8,640"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22848,1516977,Fundamental Service Oriented Arch (SOA) Securi...,/course/fundamental-service-oriented-arch-soa-...,True,16,3.25000,2.65702,2.65702,2,False,0,2,2018-01-19T09:03:46Z,2018-01-28T09:20:37Z,455.0,INR,₹455,1280.0,INR,"₹1,280"
22849,1479824,Linux Certification for Experts - Practice Tes...,/course/linux-certification-for-beginners-prac...,True,15,4.00000,3.56818,3.56818,2,False,0,2,2017-12-23T12:44:39Z,2017-12-24T07:38:36Z,455.0,INR,₹455,1280.0,INR,"₹1,280"
22850,1879598,SAP SuccessFactors Employee Central Payroll Fu...,/course/public-transport-management-systems/,True,19,2.75000,2.70354,2.70354,2,False,5,0,2018-08-27T14:43:42Z,2018-09-19T23:19:18Z,NaN,NaN,NaN,1280.0,INR,"₹1,280"
22851,1940616,Comptia Linux+ / LPIC-1 (102-400),/course/comptia-linux-lpic-1-102-400/,True,1082,3.75000,3.72059,3.72059,2,False,31,0,2018-09-30T15:11:27Z,2018-12-11T16:22:32Z,455.0,INR,₹455,1280.0,INR,"₹1,280"
22852,543712,Cisco Networking CCNA IPv6 OSPF,/course/networkingstepbystep-ipv6-ospf/,True,858,4.50000,4.48220,4.48220,2,False,24,0,2015-07-03T02:24:30Z,2015-07-07T00:01:23Z,455.0,INR,₹455,8640.0,INR,"₹8,640"

In [46]:
from surprise import Reader, Dataset, SVD
from surprise.model_selection.validation import cross_validate
reader = Reader()
data = Dataset.load_from_df(df[['num_subscribers', 'title', 'rating']], reader)
svd = SVD()

In [47]:
cross_validate(svd, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std
RMSE (testset)    0.7368  0.7070  0.7035  0.7080  0.7388  0.7188  0.0156
MAE (testset)     0.5196  0.5029  0.5067  0.5148  0.5099  0.5108  0.0059
Fit time          1.29    1.29    1.33    1.42    1.37    1.34    0.05
Test time         0.03    0.03    0.15    0.04    0.03    0.05    0.05

{'fit_time': (1.294787883758545,
  1.2887532711029053,
  1.328061580657959,
  1.418605089187622,
  1.3665711879730225),
 'test_mae': array([0.51958444, 0.50292839, 0.50672614, 0.51477054, 0.5098824 ]),
 'test_rmse': array([0.73681499, 0.70697734, 0.70346054, 0.70795098, 0.73883341]),
 'test_time': (0.030303478240966797,
  0.02925395965576172,
  0.14876580238342285,
  0.035291194915771484,
  0.029984712600708008)}

In [48]:
train_set = data.build_full_trainset()
svd.fit(train_set)

In [49]:
val = df_title.copy()
val['Estimate_Score'] = val['id'].apply(lambda x: svd.predict(1, x).est)
val = val.sort_values(by=['Estimate_Score'], ascending=False)
val

,,,,,,,,,,,,,,,,,id,title,rating,Estimate_Score
id,title,url,is_paid,num_subscribers,avg_rating,avg_rating_recent,rating,num_reviews,is_wishlisted,num_published_lectures,num_published_practice_tests,created,published_time,discount_price__amount,discount_price__currency,discount_price__price_string,price_detail__amount,price_detail__currency,price_detail__price_string,1
2453718,The Complete Salesforce Advanced Administrator Certification,/course/the-complete-salesforce-advanced-administrator-certification/,True,3839,4.46078,4.41343,4.41343,211,False,223,0,2019-07-11T01:33:33Z,2019-07-17T18:27:05Z,455.0,INR,â¹455,8640.0,INR,"â¹8,640",1
979026,Learn geographic information systems (GIS) with QGIS,/course/learnqgis/,True,1557,3.85,3.90714,3.90714,208,False,14,0,2016-10-08T15:49:33Z,2016-10-12T16:47:39Z,455.0,INR,â¹455,2560.0,INR,"â¹2,560",1
1032310,MultiChain: How To Setup A Private Blockchain Using AWS EC2,/course/multichain-how-to-setup-private-blockchain-using-aws-ec2/,True,1252,3.4,3.6809,3.6809,208,False,13,0,2016-12-05T10:30:38Z,2016-12-12T16:10:28Z,455.0,INR,â¹455,8320.0,INR,"â¹8,320",1
2075672,Ethical Hacking: For Beginners,/course/hack-passwords-saved-in-system-web-browser-email-application/,True,7091,4.4,4.26745,4.26745,208,False,41,0,2018-12-08T19:23:57Z,2018-12-21T18:24:37Z,455.0,INR,â¹455,1280.0,INR,"â¹1,280",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1684070,Stock Investing Level 2: Swimming In Cash,/course/stock-investing-level-2/,True,345,4.55556,4.54106,4.54106,9,False,14,0,2018-05-09T09:50:29Z,2018-06-18T16:05:32Z,455.0,INR,â¹455,1280.0,INR,"â¹1,280",1
1695434,Managing People in Business,/course/managing-people-in-business/,True,41,3.44444,3.4493,3.4493,9,False,47,0,2018-05-15T07:12:54Z,2018-10-10T16:19:39Z,455.0,INR,â¹455,8640.0,INR,"â¹8,640",1
1829840,Learn To Understand Real Estate,/course/the-ultimate-guide-to-real-estate/,True,42,4.61111,4.61046,4.61046,9,False,30,0,2018-07-31T02:36:14Z,2018-08-08T17:44:42Z,455.0,INR,â¹455,1280.0,INR,"â¹1,280",1
2388382,Aerospace: How to make a FAI report pack to AS9102B,/course/aerospace-how-to-make-a-fai-report-pack-to-as9102b/,True,34,3.66667,3.52409,3.52409,9,False,12,0,2019-05-28T15:17:09Z,2019-06-06T22:41:01Z,455.0,INR,â¹455,6400.0,INR,"â¹6,400",1
543712,Cisco Networking CCNA IPv6 OSPF,/course/networkingstepbystep-ipv6-ospf/,True,858,4.5,4.4822,4.4822,2,False,24,0,2015-07-03T02:24:30Z,2015-07-07T00:01:23Z,455.0,INR,â¹455,8640.0,INR,"â¹8,640",1